gText_Birch_Welcome:: @ 82C897B
	.string "Hi! Let's hurry this up, shall we?\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This ROMhack is quite basic. Just\n"
	.string "some simple changes to make the\l"
	.string "original Emerald experience a bit\l"
	.string "more modern. Thanks for trying it!\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "What's your name?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Good luck with catching and \n"
	.string "battling different Pokémon.\l"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
